[package]
name = "av_protocol_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
rusb = "0.9"
artnet_protocol = "0.4.2"